### ISSUE TITLE
Typo in 03_letters README.MD

### ISSUE THREAD

**Issue by eastrd** [anz-bank/go-course#139]
The description in README file:
`
fmt.Println(strings.Join(sortLetters(letters("aba"))), "\n")
`

is supposed to be
`
fmt.Println(strings.Join(sortLetters(letters("aba")), "\n"))
`

**Comment by anzboi** [comment]
Great catch 👍 , fix coming.

**Comment by anzboi** [comment]
Great catch 👍 , fix coming.

**Comment by anzboi** [comment]
Fixed
