### ISSUE TITLE
Lab 1 - fibonacci series

### ISSUE THREAD

**Issue by juliaogris** [anz-bank/go-course#24]
- [ ] Create an executable go program in directory 01_fib
- [ ] Write a function that prints the first n Fibonacci numbers
```
func fib(n int)
```
- [ ] Call fib(7) in main to print
```
1
1
2
3
5
8
13
```
- [ ] Bonus points: For negative n print Negafibonacci numbers.

**Comment by eobjects** [comment]
#18
