### ISSUE TITLE
re: lab 1 fib sequence -- better to decouple fibonacci sequence calculation from IO

### ISSUE THREAD

**Issue by anz-rfc** [anz-bank/go-course#37]
It's usually preferable to decouple logic from other concerns like input & output, formatting. I.e. if a function has logic to compute something, it probably shouldn't also do IO.

Why? Decoupling things into components or layers that each have fewer responsibilities usually produces code that is simpler and more re-usable.

In this case: better that the function that computes fibonacci sequence is NOT responsible for doing IO (formatting the numbers to an output stream).

For example, code to compute fibonacci sequence that also writes strings to some global variable is less likely to be usable or re-usable when compared to code that simply returns the computed sequence as a new value in some "natural" representation such as a slice of integers. If you want, you can then call some other function to format the sequence to a string, but perhaps some times you don't want to format anything to a string!

Other things that you might want to do with a fibonacci sequence:

*	sum the numbers in the sequence
*	find the max of the numbers in the sequence
*	transform the sequence in some way -- e.g. add 7 to all of the values, or produce the sequence of cumulative sums of the sequence (`1 1 2 3 5 8 13 ... -->  0 1 2 4 7 12 20 33 ...`)

It's much easier to do this if the sequence is represented as an array or slice of numbers, instead of as a formatted string!

**Comment by camscale** [comment]
This is good advice @anz-rfc but this lab does precede the lesson on slices/arrays. Perhaps after that lesson, people can come back and re-think the lab if they have time.

**Comment by juliaogris** [comment]
@anz-rfc - totally agreed, @camh-anz already guessed the reason behind IO inside fib:
We haven't _learned_ slices yet but people seem to use them anyway.
Good idea to revisit

**Comment by juliaogris** [comment]
Addressed for lab 3 in https://github.com/anz-bank/go-slides/pull/22
